/**
 * 研究雷达。
 *
 * Every ResearchItem states what its design can support and what it cannot,
 * with equal weight — an effect size without its limitation is a claim, not a
 * finding. Preprints are labelled as un-reviewed everywhere they appear.
 *
 *
 * All journals, bodies and platforms are fictional.
 */
import type { ResearchItem } from '../types'

export const RESEARCH: ResearchItem[] = [
  {
    id: 'res-001',
    title: '急诊科普遍筛查所得的亲密关系暴力就诊率：塞尔瓦联邦四区域横断面研究',
    body: '塞尔瓦国家卫生研究所',
    publisher: '塞尔瓦国家卫生研究所',
    type: 'peer-reviewed',
    date: '2025-11-12',
    topics: ['violence', 'equality'],
    summary: '在四个区域的急诊科实施统一筛查问卷，得出按区域分列的就诊率与 95% 置信区间；区域间差距大于此前行政数据所显示的差距。',
    strength: '筛查工具、抽样框与拒答率全部公开，四个区域使用同一问卷与同一培训流程，因而区域间比较是有意义的。',
    limitation: '横断面设计无法确立因果方向；样本仅覆盖已到达急诊科的人，未就医者与就医后未披露者均不在其中，偏差方向已知且向下。',
    sourceId: 'src-selva-health-er-study-2025',
    demo: true,
  },
  {
    id: 'res-002',
    title: '跨性别医疗服务的证据分级：方法学综述',
    body: '《跨区域社会医学评论》',
    publisher: '《跨区域社会医学评论》',
    type: 'systematic-review',
    date: '2025-09-30',
    topics: ['trans', 'movement'],
    summary: '系统检索并按统一标准重新评级了该领域的干预研究，说明为何在难以随机化的临床领域，常规证据分级工具会系统性地把结论压低。',
    strength: '检索策略、纳入排除标准与评级分歧的处理方式全部公开，重新评级过程可复现。',
    limitation: '综述评的是证据强度，不是干预效果；把「证据等级低」读成「干预无效」是对本文最常见的误用，作者在讨论部分明确写出了这一点。',
    sourceId: 'src-transregional-trans-care-review-2025',
    demo: true,
  },
  {
    id: 'res-003',
    title: '孕产照护可及性与行程距离：跨辖区队列研究',
    body: '《跨区域社会医学评论》',
    publisher: '《跨区域社会医学评论》',
    type: 'peer-reviewed',
    date: '2025-06-18',
    topics: ['repro', 'equality'],
    summary: '追踪三个辖区的孕产照护使用情况，报告行程距离与首次产检时间之间的关联，并按收入与户籍状态分层。',
    strength: '队列设计与分层分析使得「距离」与「贫困」的效应可以部分分离；失访率与失访者特征均已报告。',
    limitation: '三个辖区的行政边界与统计口径不同，跨辖区的绝对数值不可直接比较；无证件居民在抽样框中系统性缺失。',
    sourceId: 'src-transregional-maternal-study-2025',
    demo: true,
  },
  {
    id: 'res-004',
    title: '避孕服务中断与后续就诊模式：预印本',
    body: '塞尔瓦公共卫生预印本平台',
    publisher: '塞尔瓦公共卫生预印本平台',
    type: 'preprint',
    date: '2026-05-04',
    topics: ['repro'],
    summary: '报告一次服务中断前后就诊模式的变化，作者称中断与后续就诊下降存在关联。',
    strength: '数据来自单一支付方的完整就诊记录，覆盖面在该辖区内接近全量。',
    limitation: '**未经同行评审**。第二版已于 2026-08-24 上线且表格有改动，与第一版的结论不完全一致；在同行评审完成前，本站不用它支撑任何事实陈述。',
    sourceId: 'src-selva-preprint-contraception-2026',
    demo: true,
  },
  {
    id: 'res-005',
    title: '照护劳动的时间分配与劳动参与：跨辖区调查再分析',
    body: '《跨区域社会医学评论》',
    publisher: '《跨区域社会医学评论》',
    type: 'peer-reviewed',
    date: '2026-02-20',
    topics: ['equality', 'movement'],
    summary: '合并六个辖区的时间使用调查，估计无偿照护时间与劳动参与率之间的关联，并讨论口径差异带来的偏误。',
    strength: '再分析使用原始微观数据而非已发表的汇总值，口径调整过程逐项公开。',
    limitation: '六个辖区的「照护」定义并不一致，作者的调和方案本身是一项假设；对合并后的绝对数值应谨慎，趋势比水平更可靠。',
    sourceId: 'src-transregional-care-labour-2026',
    demo: true,
  },
  {
    id: 'res-006',
    title: '协同网络骚扰的识别方法与误判率',
    body: '北屿大学网络研究组',
    publisher: '北屿大学网络研究组',
    type: 'peer-reviewed',
    date: '2025-08-08',
    topics: ['hate', 'movement'],
    summary: '比较五种识别协同行为的方法，报告各自的误判率，并说明在缺乏平台内部数据时哪些结论无法成立。',
    strength: '在有标注真值的数据集上评估，误判率是实测而非估计。',
    limitation: '外部研究者无法取得账号注册与设备信息，因而「同一批人在协调」这类结论在方法上不可达；本研究能支持的最强表述是「行为模式高度相似」。',
    sourceId: 'src-norhold-online-abuse-study-2025',
    demo: true,
  },
  {
    id: 'res-007',
    title: '法定性别变更程序的步骤数与完成率：跨辖区指数',
    body: '泛洲人权理事会秘书处',
    publisher: '泛洲人权理事会秘书处',
    type: 'official-statistics',
    date: '2026-04-15',
    topics: ['trans', 'rights'],
    summary: '按统一编码规则统计各辖区完成法律性别变更所需的法定步骤数，并与实际完成率对照。',
    strength: '编码规则与逐辖区的原始条文引用一并公布，任何人都可以重编一遍。',
    limitation: '统计的是法定步骤，不是实际耗时；登记处的裁量与地方实践差异不在指数内，判决与执行之间的落差因此看不出来。',
    sourceId: 'src-pancont-recognition-index-2026',
    demo: true,
  },
  {
    id: 'res-008',
    title: '庇护程序中以性倾向为由的申请：一审结果构成',
    body: '塞尔瓦庇护法庭统计处',
    publisher: '塞尔瓦庇护法庭统计处',
    type: 'official-statistics',
    date: '2026-03-11',
    topics: ['displacement', 'rights'],
    summary: '按申请理由分列的一审结果构成，含驳回理由的分类统计。',
    strength: '来自法庭自身的案件管理系统，覆盖全量一审案件，分类规则随表公布。',
    limitation: '「可信度不足」是一个汇总类别，其下的具体判断依据不在公开数据中；因此本数据能显示结果分布，不能解释结果成因。',
    sourceId: 'src-selva-asylum-tribunal-2026',
    demo: true,
  },
  {
    id: 'res-009',
    title: '登记庇护床位容量与人口比：2026 年跨辖区盘点',
    body: '泛洲人权理事会秘书处',
    publisher: '泛洲人权理事会秘书处',
    type: 'official-statistics',
    date: '2026-07-02',
    topics: ['violence', 'equality'],
    summary: '各辖区登记在册的庇护床位数与成年女性人口之比，附各辖区的登记标准说明。',
    strength: '登记标准差异被单独列出，而不是被平均掉，因此读者可以判断哪些比较是有效的。',
    limitation: '只统计登记在册的床位，不含非正式安置；「有床位」不等于「可进入」，语言、证件与地理可及性均不在内。',
    sourceId: 'src-pancont-shelter-capacity-2026',
    demo: true,
  },
  {
    id: 'res-010',
    title: '运动内部资源分配的田野研究：三个辖区的组织访谈',
    body: '《跨区域社会医学评论》',
    publisher: '《跨区域社会医学评论》',
    type: 'peer-reviewed',
    date: '2025-12-05',
    topics: ['movement'],
    summary: '通过组织层面的半结构访谈，描述资金申请、评审与分配中的实际约束，并归纳三种彼此冲突的公平观。',
    strength: '访谈提纲、编码簿与不同意见的处理方式公开，质性研究少见地做到了可审计。',
    limitation: '三个辖区、42 个组织的样本不足以支持任何比例性结论；本研究能说明「存在哪些立场」，不能说明「各占多少」。',
    sourceId: 'src-transregional-movement-fieldwork-2025',
    demo: true,
  },
  {
    id: 'res-011',
    title: '中学阶段女生净入学率的县际差异：卡利桑邦 2025 年学籍统计',
    body: '卡利桑邦教育统计处',
    publisher: '卡利桑邦教育统计处',
    type: 'official-statistics',
    date: '2025-10-22',
    topics: ['equality'],
    summary: '按县分组的中学女生净入学率，附学籍登记规则与转学处理方式。',
    strength: '基于全量学籍登记而非抽样，县际比较在同一规则下进行。',
    limitation: '净入学率以学籍为准，长期缺课但未注销学籍者仍计为在学；因此本数据会系统性高估实际就学。',
    sourceId: 'src-kalisan-enrolment-stats-2025',
    demo: true,
  },
  {
    id: 'res-012',
    title: '跨性别医疗首次评估等待时长：北屿五年追踪',
    body: '北屿跨性别健康联盟',
    publisher: '北屿跨性别健康联盟',
    type: 'ngo-study',
    date: '2026-06-30',
    topics: ['trans', 'equality'],
    summary: '连续五年以同一口径收集各服务点的首次评估等待时长中位数与四分位距。',
    strength: '五年同口径，收集方法与各点应答率逐年公布，趋势判断因此可靠。',
    limitation: '数据来自服务提供方自报，未经独立审计；已放弃排队者不在分母中，实际等待体验可能比中位数更差。',
    sourceId: 'src-norhold-trans-health-alliance-2026',
    demo: true,
  },
  {
    id: 'res-013',
    title: '平台对被举报骚扰内容的处置构成：2026 上半年透明度报告',
    body: '潮线网络',
    publisher: '潮线网络',
    type: 'ngo-study',
    date: '2026-06-15',
    topics: ['hate'],
    summary: '平台自行发布的举报处置分类统计，含处置时长分布。',
    strength: '是目前唯一覆盖全量举报的数据来源，分类定义随报告公布。',
    limitation: '由平台自行统计、自行分类，无独立核验；「已处置」不等于「处置得当」，也不含未被举报的内容。作为利益相关方的自报数据使用。',
    sourceId: 'src-tideline-platform-transparency-2026',
    demo: true,
  },
  {
    id: 'res-014',
    title: '跨辖区行政计数的可比性：方法说明（预印本）',
    body: '《跨区域社会医学评论》方法组',
    publisher: '《跨区域社会医学评论》方法组',
    type: 'preprint',
    date: '2026-07-19',
    topics: ['violence', 'equality', 'movement'],
    summary: '提出一套判断两个辖区的行政统计是否可比的检查清单，并用三组实例演示不可比的常见原因。',
    strength: '检查清单可直接应用，实例的原始数据一并提供。',
    limitation: '**未经同行评审**。清单本身尚未在独立数据集上验证，作者也未主张它是完备的。',
    sourceId: 'src-pool-transregional-methods-note-2026',
    demo: true,
  },
  {
    id: 'res-015',
    title: '性别薪酬差距的口径与解释：泛洲平等专家组说明',
    body: '泛洲平等事务专家组',
    publisher: '泛洲平等事务专家组',
    type: 'official-statistics',
    date: '2026-05-28',
    topics: ['equality'],
    summary: '说明未调整差距与调整后差距各自测量什么，并给出跨辖区的未调整中位数差距。',
    strength: '同时公布两种口径与各自的计算方式，使最常见的误读有了可引用的纠正依据。',
    limitation: '未调整差距不能支撑任何关于个别雇主歧视的结论；把它读成「同工不同酬的幅度」是错误的，本说明对此有明确表述。',
    sourceId: 'src-pancont-equality-panel-2026',
    demo: true,
  },
]
