/**
 * 今日信号 — the intake feed for 2026-08-31.
 *
 * A signal is NOT an article. It is what the automated desk saw after
 * collecting across jurisdictions and languages and merging duplicate
 * reports into clusters. Headlines here are terse intake lines, corroboration
 * is stated honestly, and a spiked story keeps its reason on the record
 * rather than disappearing.
 *
 * All jurisdictions, outlets and organisations are fictional.
 */
import type { Signal } from '../types'

export const SIGNALS: Signal[] = [
  /* ------------------------- the day's top five ------------------------- */
  {
    id: 'sig-001',
    headline: '韦拉宪法法庭第214/2026号判决后，两家民事登记处仍要求提交医疗证明',
    country: '韦拉共和国', region: '南陆', language: 'es',
    topics: ['trans', 'rights'],
    firstSeen: '2026-08-31T01:12:00Z',
    reportCount: 9, independentSourceCount: 5, primarySourceCount: 2,
    newsValue: 94,
    newsValueBasis: '判决已生效两个月，但两处登记实践未变；这是「判决与执行之间的落差」首次有可核对的书面记录。',
    corroboration: 'multi-source',
    status: 'drafted', linkedArticleId: 'art-veyra',
    mergedFrom: ['海岸线报', '南陆通讯', '韦拉法律观察', '边界之声', '米拉妇女法律中心通报', '公民登记月报', '南方电台网站'],
    demo: true,
  },
  {
    id: 'sig-002',
    headline: '卡利桑邦统计局补发 2024 年家暴统计口径变更说明，但未公布方法附录',
    country: '卡利桑邦', region: '内陆高原', language: 'hi',
    topics: ['violence', 'equality'],
    firstSeen: '2026-08-31T02:40:00Z',
    reportCount: 7, independentSourceCount: 4, primarySourceCount: 1,
    newsValue: 91,
    newsValueBasis: '直接关系到正在流传的「家暴案件激增四成」说法；口径说明是可核对的一手文件，方法附录仍缺失。',
    corroboration: 'multi-source',
    status: 'drafted', linkedArticleId: 'art-kalisan',
    mergedFrom: ['高原日报', '卡利桑公共广播', '数据与治理通讯', '女性法律援助网络月报', '内陆观察'],
    demo: true,
  },
  {
    id: 'sig-003',
    headline: '马兰岛法院就一起性暴力案件延长报道限制令，范围扩及庭审排期',
    country: '马兰岛自治区', region: '群岛', language: 'pt',
    topics: ['violence', 'rights'],
    firstSeen: '2026-08-31T03:05:00Z',
    reportCount: 6, independentSourceCount: 3, primarySourceCount: 2,
    newsValue: 89,
    newsValueBasis: '限制令原文与议会辩论记录均可取得；涉及未成年人身份保护与公众知情权的直接冲突。',
    corroboration: 'multi-source',
    status: 'drafted', linkedArticleId: 'art-maran',
    mergedFrom: ['群岛纪事', '马兰岛媒体协会通报', '沿岸集体通讯', '海事法律评论'],
    demo: true,
  },
  {
    id: 'sig-004',
    headline: '阿米拉特庇护署内部培训材料流出，载有「可信度评估」的提问清单',
    country: '阿米拉特王国', region: '西陆', language: 'ar',
    topics: ['displacement', 'rights', 'hate'],
    firstSeen: '2026-08-31T00:48:00Z',
    reportCount: 5, independentSourceCount: 3, primarySourceCount: 0,
    newsValue: 88,
    newsValueBasis: '若材料属实，将是该程序运作方式的首份文件证据；但流出途径不明，尚无机构确认其真实性。',
    corroboration: 'contested',
    status: 'drafted', linkedArticleId: 'art-amirat',
    mergedFrom: ['边界之声', '西陆人权简报', '难民法律诊所通讯'],
    demo: true,
  },
  {
    id: 'sig-005',
    headline: '图兰一批账号在四小时内对同一批记者发出近万条内容相近的信息',
    country: '图兰共和国', region: '中陆', language: 'tr',
    topics: ['hate', 'movement'],
    firstSeen: '2026-08-31T04:22:00Z',
    reportCount: 8, independentSourceCount: 4, primarySourceCount: 1,
    newsValue: 86,
    newsValueBasis: '平台透明度报告给出可核对的处置数据；但「谁在协调」目前只有推断，没有证据。',
    corroboration: 'multi-source',
    status: 'drafted', linkedArticleId: 'art-turan',
    mergedFrom: ['图兰独立新闻社', '中陆数字权利中心', '记者保护通讯', '潮线网络透明度报告', '本地事实核查小组', '大学网络研究组'],
    demo: true,
  },

  /* ------------------------------ the rest ------------------------------ */
  {
    id: 'sig-006',
    headline: '塞尔瓦劳动法庭就一起同工同酬案作出一审判决，认定举证责任倒置适用',
    country: '塞尔瓦联邦', region: '南陆', language: 'es',
    topics: ['equality'],
    firstSeen: '2026-08-31T05:30:00Z',
    reportCount: 4, independentSourceCount: 3, primarySourceCount: 1,
    newsValue: 78,
    newsValueBasis: '判决书全文已公开，可能改变同类案件的举证结构；上诉期未过。',
    corroboration: 'multi-source', status: 'new',
    mergedFrom: ['塞尔瓦法律公报摘要', '南陆劳工通讯', '劳动法评论'],
    demo: true,
  },
  {
    id: 'sig-007',
    headline: '北屿跨性别医疗联盟发布首次评估等待时长的第五年数据',
    country: '北屿联合王国', region: '北方群岛', language: 'en',
    topics: ['trans', 'equality'],
    firstSeen: '2026-08-31T02:05:00Z',
    reportCount: 6, independentSourceCount: 4, primarySourceCount: 1,
    newsValue: 81,
    newsValueBasis: '连续五年同口径数据，方法公开；等待时长中位数与政策承诺之间的差距可直接核对。',
    corroboration: 'multi-source', status: 'clustered',
    mergedFrom: ['北屿公共卫生通讯', '群岛日报', '跨性别健康联盟公告', '医疗政策季刊网站', '北方电台'],
    demo: true,
  },
  {
    id: 'sig-008',
    headline: '东埃斯特里亚卫生部就跨性别医疗指南修订召开第三轮听证',
    country: '东埃斯特里亚', region: '中陆', language: 'ru',
    topics: ['trans', 'movement'],
    firstSeen: '2026-08-30T22:15:00Z',
    reportCount: 5, independentSourceCount: 2, primarySourceCount: 1,
    newsValue: 76,
    newsValueBasis: '听证记录部分公开；两个临床团体对证据分级的分歧首次以书面形式提交。',
    corroboration: 'contested',
    status: 'drafted', linkedArticleId: 'art-estria',
    mergedFrom: ['东埃斯特里亚国家通讯社', '中陆医学通讯', '临床指南观察'],
    demo: true,
  },
  {
    id: 'sig-009',
    headline: '韦拉国会性别平等课程法案进入二读，三项条文被要求逐条表决',
    country: '韦拉共和国', region: '南陆', language: 'es',
    topics: ['equality', 'rights'],
    firstSeen: '2026-08-30T20:40:00Z',
    reportCount: 7, independentSourceCount: 4, primarySourceCount: 2,
    newsValue: 84,
    newsValueBasis: '法案条文与逐条修正记录均已刊出；围绕第 9、12、17 条的三种说法可直接对照原文核查。',
    corroboration: 'multi-source',
    status: 'drafted', linkedArticleId: 'art-curriculum',
    mergedFrom: ['韦拉立法公报', '海岸线报', '南陆通讯', '教育政策通讯', '家长团体联合声明'],
    demo: true,
  },
  {
    id: 'sig-010',
    headline: '泛洲人权理事会就生育权发布结论性意见，点名三个辖区的孕产照护缺口',
    country: '泛洲（跨国机构）', region: '跨国', language: 'fr',
    topics: ['repro', 'rights'],
    firstSeen: '2026-08-30T18:10:00Z',
    reportCount: 11, independentSourceCount: 6, primarySourceCount: 1,
    newsValue: 83,
    newsValueBasis: '结论性意见全文可取得，并附各辖区回应；是少数能跨辖区比较的一手材料。',
    corroboration: 'multi-source', status: 'clustered',
    mergedFrom: ['泛洲新闻处', '南陆通讯', '群岛纪事', '西陆人权简报', '国际卫生通讯', '边界之声', '高原日报', '北方电台'],
    demo: true,
  },
  {
    id: 'sig-011',
    headline: '塞尔瓦一处远程医疗平台暂停终止妊娠咨询服务，未说明理由',
    country: '塞尔瓦联邦', region: '南陆', language: 'pt',
    topics: ['repro', 'rights'],
    firstSeen: '2026-08-31T06:02:00Z',
    reportCount: 5, independentSourceCount: 3, primarySourceCount: 0,
    newsValue: 80,
    newsValueBasis: '与已发布报道直接相关，可能触发更新；但暂停原因目前只有平台一句话公告。',
    corroboration: 'multi-source',
    status: 'drafted', linkedArticleId: 'art-selva',
    mergedFrom: ['南陆通讯', '塞尔瓦健康观察', '女性健康网络通报', '地方广播网站'],
    demo: true,
  },
  {
    id: 'sig-012',
    headline: '泛洲基金分配审查的第二份补充材料公布，包含各组织的申请成功率',
    country: '泛洲（跨国机构）', region: '跨国', language: 'en',
    topics: ['movement'],
    firstSeen: '2026-08-30T16:25:00Z',
    reportCount: 4, independentSourceCount: 3, primarySourceCount: 1,
    newsValue: 74,
    newsValueBasis: '补充材料可直接验证正在流传的成功率说法；原始问卷题项清单同时公布。',
    corroboration: 'multi-source',
    status: 'drafted', linkedArticleId: 'art-funding',
    mergedFrom: ['泛洲新闻处', '公益治理通讯', '基金观察'],
    demo: true,
  },
  {
    id: 'sig-013',
    headline: '西埃斯特里亚审计署报告指无国籍登记系统漏登约一成新生儿',
    country: '西埃斯特里亚', region: '中陆', language: 'ru',
    topics: ['displacement', 'equality'],
    firstSeen: '2026-08-30T14:50:00Z',
    reportCount: 3, independentSourceCount: 2, primarySourceCount: 1,
    newsValue: 77,
    newsValueBasis: '审计署方法与抽样公开；漏登比例可与登记处自身数据交叉核对。',
    corroboration: 'multi-source', status: 'clustered',
    mergedFrom: ['西陆审计通讯', '中陆人权简报'],
    demo: true,
  },
  {
    id: 'sig-014',
    headline: '北屿仇恨犯罪统计首次单列针对跨性别者的线下袭击',
    country: '北屿联合王国', region: '北方群岛', language: 'en',
    topics: ['hate', 'trans'],
    firstSeen: '2026-08-30T12:35:00Z',
    reportCount: 6, independentSourceCount: 4, primarySourceCount: 1,
    newsValue: 79,
    newsValueBasis: '分类变更本身就是新闻，同时使得跨年度比较不再成立——这一点多数报道没有说。',
    corroboration: 'multi-source', status: 'clustered',
    mergedFrom: ['群岛日报', '北屿平等事务监察署公告', '北方电台', '警务统计通讯', '社区安全网络'],
    demo: true,
  },
  {
    id: 'sig-015',
    headline: '马兰岛沿岸集体称一处海上救援转交程序对单身女性适用不同标准',
    country: '马兰岛自治区', region: '群岛', language: 'pt',
    topics: ['displacement', 'violence'],
    firstSeen: '2026-08-30T09:20:00Z',
    reportCount: 2, independentSourceCount: 1, primarySourceCount: 0,
    newsValue: 62,
    newsValueBasis: '若属实则涉及系统性差别待遇，但目前只有一家组织的转述，程序文件未公开。',
    corroboration: 'single-source', status: 'new',
    mergedFrom: ['沿岸集体通讯'],
    demo: true,
  },
  {
    id: 'sig-016',
    headline: '图兰一家媒体就此前关于妇女组织资金来源的报道刊发更正',
    country: '图兰共和国', region: '中陆', language: 'tr',
    topics: ['movement', 'hate'],
    firstSeen: '2026-08-30T08:05:00Z',
    reportCount: 3, independentSourceCount: 2, primarySourceCount: 1,
    newsValue: 58,
    newsValueBasis: '更正本身可取得；对评估该媒体既往报道的可靠性有直接价值。',
    corroboration: 'multi-source', status: 'clustered',
    mergedFrom: ['图兰独立新闻社', '媒体问责通讯'],
    demo: true,
  },
  {
    id: 'sig-017',
    headline: '卡利桑一处庇护所预算被削减，床位数尚未公布',
    country: '卡利桑邦', region: '内陆高原', language: 'hi',
    topics: ['violence', 'equality'],
    firstSeen: '2026-08-30T07:40:00Z',
    reportCount: 4, independentSourceCount: 2, primarySourceCount: 0,
    newsValue: 66,
    newsValueBasis: '预算文件尚未公开，床位影响无法量化；需要等待预算附表。',
    corroboration: 'multi-source', status: 'new',
    mergedFrom: ['高原日报', '女性法律援助网络月报', '地方议会旁听记录'],
    demo: true,
  },
  {
    id: 'sig-018',
    headline: '阿米拉特一份 2023 年刑法条文的英译本被广泛引用，译文与原文有出入',
    country: '阿米拉特王国', region: '西陆', language: 'ar',
    topics: ['rights', 'displacement'],
    firstSeen: '2026-08-29T21:10:00Z',
    reportCount: 6, independentSourceCount: 3, primarySourceCount: 1,
    newsValue: 71,
    newsValueBasis: '原文可取得，可逐条比对；错误译文已进入多篇国际报道。',
    corroboration: 'multi-source', status: 'clustered',
    mergedFrom: ['西陆人权简报', '边界之声', '法律翻译观察', '难民法律诊所通讯'],
    demo: true,
  },
  {
    id: 'sig-019',
    headline: '一段称某辖区将强制登记跨性别者的通函截图在多个平台流传',
    country: '多辖区（跨国比较）', region: '跨国', language: 'en',
    topics: ['trans', 'hate'],
    firstSeen: '2026-08-31T03:55:00Z',
    reportCount: 12, independentSourceCount: 0, primarySourceCount: 0,
    newsValue: 69,
    newsValueBasis: '传播量大且仍在上升；但截图无法回溯到任何可查的原始记录，属于需要核查而非报道的对象。',
    corroboration: 'unverified', status: 'clustered',
    mergedFrom: ['聚合账号截图集', '匿名论坛转贴', '两个视频平台的搬运号'],
    demo: true,
  },
  {
    id: 'sig-020',
    headline: '北屿薪酬透明法迟报雇主名单更新，新增 37 家',
    country: '北屿联合王国', region: '北方群岛', language: 'en',
    topics: ['equality'],
    firstSeen: '2026-08-30T11:15:00Z',
    reportCount: 3, independentSourceCount: 2, primarySourceCount: 1,
    newsValue: 55,
    newsValueBasis: '名单为一手记录且可逐家核对，但增量属常规更新，新闻价值有限。',
    corroboration: 'multi-source', status: 'clustered',
    mergedFrom: ['北屿平等事务监察署公告', '群岛日报'],
    demo: true,
  },

  /* --------------------------- spiked, on the record -------------------- */
  {
    id: 'sig-021',
    headline: '有说法称某国际组织将大幅削减对女性主义组织的资助',
    country: '泛洲（跨国机构）', region: '跨国', language: 'en',
    topics: ['movement'],
    firstSeen: '2026-08-30T19:30:00Z',
    reportCount: 5, independentSourceCount: 1, primarySourceCount: 0,
    newsValue: 44,
    newsValueBasis: '传播中的说法，但所有报道均可回溯到同一匿名转述。',
    corroboration: 'single-source', status: 'declined',
    declineReason: '唯一来源为匿名转述，原始预算文件不可得；已转入「可疑说法」观察，待有一手材料再评估。',
    mergedFrom: ['基金观察'],
    demo: true,
  },
  {
    id: 'sig-022',
    headline: '一名公众人物在访谈中就性别议题发表争议言论',
    country: '北屿联合王国', region: '北方群岛', language: 'en',
    topics: ['movement', 'hate'],
    firstSeen: '2026-08-30T17:05:00Z',
    reportCount: 14, independentSourceCount: 6, primarySourceCount: 0,
    newsValue: 38,
    newsValueBasis: '传播量高，但没有任何可核查的事实主张，也没有政策或法律后果。',
    corroboration: 'multi-source', status: 'declined',
    declineReason: '争议本身不构成选题：无可核查的事实主张、无制度后果。报道它只会放大言论本身。',
    mergedFrom: ['群岛日报', '北方电台', '八家聚合站点转载'],
    demo: true,
  },
  {
    id: 'sig-023',
    headline: '塞尔瓦某地一起家庭暴力案件的现场细节在本地论坛流传',
    country: '塞尔瓦联邦', region: '南陆', language: 'pt',
    topics: ['violence'],
    firstSeen: '2026-08-30T13:45:00Z',
    reportCount: 9, independentSourceCount: 1, primarySourceCount: 0,
    newsValue: 31,
    newsValueBasis: '仅有猎奇性细节在流传，无制度层面的可报道内容。',
    corroboration: 'single-source', status: 'declined',
    declineReason: '流传内容包含可识别当事人的细节与侵害过程描述。按创伤知情准则，本站不报道此类内容，也不转述细节；已记录以备日后出现制度层面的进展。',
    mergedFrom: ['本地论坛转贴'],
    demo: true,
  },
  {
    id: 'sig-024',
    headline: '与前日「北屿仇恨犯罪统计分类变更」重复的一组报道',
    country: '北屿联合王国', region: '北方群岛', language: 'en',
    topics: ['hate'],
    firstSeen: '2026-08-30T10:00:00Z',
    reportCount: 5, independentSourceCount: 3, primarySourceCount: 0,
    newsValue: 29,
    newsValueBasis: '与 sig-014 同源，无新增事实。',
    corroboration: 'multi-source', status: 'declined',
    declineReason: '与 sig-014 重复，已并入该聚类；保留记录以说明去重结果。',
    mergedFrom: ['三家聚合站点', '两家地方电台网站'],
    demo: true,
  },
]
