/**
 * PRISM 棱镜 — 共享引用登记表（演示数据）
 *
 * EVERYTHING IN THIS FILE IS FICTIONAL DEMONSTRATION DATA.
 * 本文件中的每一条记录都是为原型演示而虚构的：司法辖区、法院、议会、统计机构、
 * 期刊、通讯社、民间组织与平台全部不存在；所有 `url` 位于 RFC 2606 保留的
 * `.invalid` 顶级域，永远无法解析；每条记录都带有 `demo: true`。
 * 这里没有任何真实报道、真实引用、真实案号或真实人物的言论。
 *
 * 结构约定
 * - id：`src-<辖区或机构缩写>-<主题>-<年份>`，仅使用小写字母、数字与连字符。
 * - 以 `src-pool-` 开头的记录是「候选来源池」：目前没有任何稿件使用它们，
 *   供审核台的「要求增加来源」流程从中挑选。
 * - `credibility`（0–100）永远由 `credibilityBasis` 中的一句具体理由支撑：
 *   方法透明度、原始记录可及性、独立性、更正记录与既往表现。
 * - `caution` 只出现在编辑必须格外小心的来源上（单一匿名帖、利益相关方声明、
 *   有更正问题的媒体、未经同行评审的预印本、受新闻限制辖区的官方机构）。
 *   审核台的「最弱来源」与「证据存在冲突」界面依赖这些记录。
 */
import type { Source } from '../types'

export const SOURCES: Source[] = [
  /* ==================================================================== *
   * rights — 女性主义与 LGBTQIA+ 权利
   * ==================================================================== */
  {
    id: 'src-veyra-court-ruling-2026',
    title: 'Sentencia 214/2026 — Sala Constitucional de Veyra（韦拉宪法法庭第214/2026号判决）',
    publisher: '韦拉最高法院宪法法庭 (Constitutional Chamber, Supreme Court of Veyra)',
    sourceType: 'court-ruling',
    tier: 'primary',
    url: 'https://demo.prism.invalid/veyra-constitutional-214-2026',
    date: '2026-06-18',
    language: 'es',
    country: '韦拉共和国',
    credibility: 97,
    credibilityBasis: '判决全文、三份异议意见与庭审笔录在宣判当日由法院公报完整公开，可逐段核对法庭据以裁判的事实认定与法条适用。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
    notes: '第 41–58 段处理民间团体登记要求的合宪性；第 72 段是本站引用的核心表述。',
  },
  {
    id: 'src-veyra-assoc-bill-2025',
    title: 'Proyecto de Ley 88/2025 sobre el registro de asociaciones civiles（韦拉第88/2025号民间团体登记法案）',
    publisher: '韦拉共和国国会立法公报 (Legislative Gazette of the Republic of Veyra)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/veyra-assoc-bill-88-2025',
    date: '2025-11-04',
    language: 'es',
    country: '韦拉共和国',
    credibility: 91,
    credibilityBasis: '立法公报刊出法案条文原文、逐条修正记录与委员会表决名单，任何引用都可回到具体条款编号验证。',
    accessedAt: '2026-08-26',
    isPrimary: true,
    demo: true,
    notes: '第 12 条与第 19 条是后来被宪法法庭部分推翻的条款。',
  },
  {
    id: 'src-norhold-equality-register-2026',
    title: 'Equality Inspectorate Register of Recognised Bodies 2026（北屿平等事务监察署认可团体登记名册 2026）',
    publisher: '北屿平等事务监察署 (Norhold Equality Inspectorate)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/norhold-equality-register-2026',
    date: '2026-05-12',
    language: 'en',
    country: '北屿联合王国',
    credibility: 89,
    credibilityBasis: '登记名册按季度更新并附带完整的字段说明与历史版本存档，被拒登记的理由也一并公布，可核对增减变化。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pancont-rights-observations-2025',
    title: 'Observations finales sur la République de Veyra（泛洲人权理事会对韦拉共和国的结论性意见）',
    publisher: '泛洲人权理事会 (Pan-Continental Human Rights Council)',
    sourceType: 'international-body',
    tier: 'primary',
    url: 'https://demo.prism.invalid/pancont-observations-veyra-2025',
    date: '2025-09-30',
    language: 'fr',
    country: '泛洲（跨国机构）',
    credibility: 93,
    credibilityBasis: '条约机构的结论性意见附有缔约国提交材料、民间组织影子报告与审议逐字记录的编号索引，每一项认定都能追到其依据。',
    accessedAt: '2026-08-24',
    isPrimary: true,
    demo: true,
    notes: '本站引用的是第 24–29 段关于结社自由的部分。',
  },
  {
    id: 'src-turan-agency-assembly-2026',
    title: 'Dernek kayıt başvurularında yeni uygulama（图兰独立新闻社：社团登记申请出现新做法）',
    publisher: '图兰独立新闻社 (Turan Independent News Agency)',
    sourceType: 'news-agency',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/turan-agency-assembly-2026',
    date: '2026-07-22',
    language: 'tr',
    country: '图兰共和国',
    credibility: 74,
    credibilityBasis: '通讯社公开署名、更正政策与消息来源分级标准，本篇引用了两份可查的登记回执，但未能取得主管部门的完整拒登清单。',
    accessedAt: '2026-08-28',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-amirat-ministry-statement-2025',
    title: 'بيان وزارة الشؤون الاجتماعية بشأن تسجيل الجمعيات（阿米拉特社会事务部关于社团登记的声明）',
    publisher: '阿米拉特王国社会事务部 (Ministry of Social Affairs, Kingdom of Amirat)',
    sourceType: 'statement',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/amirat-ministry-statement-2025',
    date: '2025-06-27',
    language: 'ar',
    country: '阿米拉特王国',
    credibility: 52,
    credibilityBasis: '声明由争议的当事一方发布，只给出结论性表述，既未附登记数据也未附被拒理由清单，无法独立验证其中任何数字。',
    accessedAt: '2026-08-26',
    isPrimary: false,
    demo: true,
    caution: '发布方是本案的当事一方。声明可以用来说明官方立场，不能用来支撑关于事实的陈述；引用时必须写明这是一方说法。',
  },
  {
    id: 'src-maran-island-media-assembly-2026',
    title: 'Pendaftaran organisasi perempuan tertunda di tiga distrik（马兰群岛回声报：三个县的妇女组织登记被搁置）',
    publisher: '马兰群岛回声报 (Maran Archipelago Echo)',
    sourceType: 'local-media',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/maran-echo-assembly-2026',
    date: '2026-08-09',
    language: 'id',
    country: '马兰岛自治区',
    credibility: 71,
    credibilityBasis: '地方报社在报道中列出了三份登记回执编号并公布了向主管部门发出的问询原文，但其中一个县的说法仅有单一信源。',
    accessedAt: '2026-08-29',
    isPrimary: false,
    demo: true,
  },

  /* ==================================================================== *
   * violence — 性暴力、家庭暴力与性骚扰
   * ==================================================================== */
  {
    id: 'src-kalisan-stats-dv-2025',
    title: 'घरेलू हिंसा प्रशासनिक रिपोर्ट 2025（卡利桑统计局家庭暴力行政通报 2025）',
    publisher: '卡利桑统计局 (Kalisan Bureau of Statistics)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/kalisan-dv-administrative-2025',
    date: '2025-12-15',
    language: 'hi',
    country: '卡利桑邦',
    credibility: 84,
    credibilityBasis: '统计局公布了完整的表格、登记点名单与口径变更说明，但仅提供汇总表、不开放去标识化的个案微数据，外部无法重算。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
    notes: '2024 年起将「同一当事人多次报案」由合并计为一案改为分别立案，前后两段不可直接比较。',
  },
  {
    id: 'src-kalisan-court-protection-2026',
    title: 'कालिसन उच्च न्यायालय — संरक्षण आदेश संदर्भ निर्णय（卡利桑高等法院保护令参考判决）',
    publisher: '卡利桑高等法院 (Kalisan High Court)',
    sourceType: 'court-ruling',
    tier: 'primary',
    url: 'https://demo.prism.invalid/kalisan-protection-order-2026',
    date: '2026-04-27',
    language: 'hi',
    country: '卡利桑邦',
    credibility: 92,
    credibilityBasis: '判决书全文公开并附上诉法院的处理结果统计附表，法院还公布了该附表的抽样与编码规则，可核对分类是否一致。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-selva-health-er-study-2025',
    title: 'Rastreio de violência por parceiro íntimo em serviços de urgência（塞尔瓦国家卫生研究所：急诊科亲密关系暴力筛查研究）',
    publisher: '塞尔瓦国家卫生研究所 (Selva National Institute of Health)',
    sourceType: 'primary-research',
    tier: 'primary',
    url: 'https://demo.prism.invalid/selva-er-screening-2025',
    date: '2025-08-19',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 88,
    credibilityBasis: '研究预先登记了分析方案，公布了筛查问卷、抽样框与置信区间计算方法，且在论文中明确报告了 14% 的筛查拒答率。',
    accessedAt: '2026-08-24',
    isPrimary: true,
    demo: true,
    notes: '样本仅覆盖到达急诊科并接受主动筛查的就诊者。',
  },
  {
    id: 'src-norhold-protection-act-2024',
    title: 'Domestic Abuse (Protection Orders) Act 2024（北屿《家庭暴力保护令法 2024》）',
    publisher: '北屿联合王国议会法典局 (Norhold Parliamentary Statute Office)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/norhold-protection-orders-act-2024',
    date: '2024-03-07',
    language: 'en',
    country: '北屿联合王国',
    credibility: 94,
    credibilityBasis: '成文法条文由法典局逐条维护并标注生效日期与后续修订，可以直接核对某一条款在特定日期的有效文本。',
    accessedAt: '2026-08-26',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-mira-legal-caseload-2026',
    title: 'Informe de casos atendidos 2025–2026（米拉妇女法律中心受理案件报告 2025–2026）',
    publisher: '米拉妇女法律中心 (Mira Women’s Legal Centre)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/mira-legal-caseload-2026',
    date: '2026-06-30',
    language: 'es',
    country: '韦拉共和国',
    credibility: 79,
    credibilityBasis: '机构公布了案件计数规则、资金来源与利益冲突声明，数字来自自身受理记录，因此只代表求助人群而非全体人群。',
    accessedAt: '2026-08-28',
    isPrimary: false,
    demo: true,
    notes: '仅覆盖主动向该中心求助的当事人，不能推及全国发生率。',
  },
  {
    id: 'src-coastline-court-report-2026',
    title: 'Audiência adiada pela terceira vez no tribunal do porto（海岸线报：港区法院庭审第三次延期）',
    publisher: '海岸线报 (Coastline Daily)',
    sourceType: 'local-media',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/coastline-court-hearing-2026',
    date: '2026-08-14',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 68,
    credibilityBasis: '记者在庭上取得排期表复印件并附出了案号，但当事双方的回应只取到一方，且报道未说明另一方是否被联系过。',
    accessedAt: '2026-08-30',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-veyra-anon-post-ruling-2026',
    title: 'Publicación anónima sobre el fallo（一则关于判决的匿名社交平台帖文）',
    publisher: '匿名账号（未署名，无机构归属）',
    sourceType: 'social-post',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/anon-post-veyra-ruling-2026',
    date: '2026-08-21',
    language: 'es',
    country: '韦拉共和国',
    credibility: 34,
    credibilityBasis: '单一匿名账号发布，无法确认发布者身份、在场与否或信息取得途径，帖文所附截图无法回溯到任何可查的原始记录。',
    accessedAt: '2026-08-29',
    isPrimary: false,
    demo: true,
    caution: '单一匿名帖文，无法核实。只能作为「某种说法正在流传」的证据，绝不可用来支撑事实陈述；若稿件依赖它，必须先找到一手记录。',
  },
  {
    id: 'src-pancont-shelter-capacity-2026',
    title: 'Enquête régionale sur les capacités d’hébergement protégé 2026（泛洲庇护床位容量区域调查 2026）',
    publisher: '泛洲人权理事会服务能力工作组 (Pan-Continental Human Rights Council, Service Capacity Working Group)',
    sourceType: 'international-body',
    tier: 'primary',
    url: 'https://demo.prism.invalid/pancont-shelter-capacity-2026',
    date: '2026-05-28',
    language: 'fr',
    country: '多辖区（跨国比较）',
    credibility: 86,
    credibilityBasis: '调查公布了各辖区的填报表原件与统一的床位定义，但依赖各辖区自行申报，且有一个辖区拒绝提供数据、已在报告中标注缺失。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
  },

  /* ==================================================================== *
   * repro — 生育权与身体自主权
   * ==================================================================== */
  {
    id: 'src-selva-abortion-access-stats-2026',
    title: 'Distância aos serviços de interrupção da gravidez 2026（塞尔瓦终止妊娠服务可及性统计 2026）',
    publisher: '塞尔瓦联邦卫生统计司 (Selva Federal Health Statistics Directorate)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/selva-service-distance-2026',
    date: '2026-03-11',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 87,
    credibilityBasis: '数据以行政区为单位公开，附有机构名录、距离计算脚本与四分位数定义，外部研究者可以用同一脚本复算。',
    accessedAt: '2026-08-24',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-transregional-maternal-study-2025',
    title: 'Maternal outcomes after delayed care authorisation: a multi-site cohort（延迟授权后的孕产结局：多点队列研究）',
    publisher: '《跨区域社会医学评论》(Transregional Review of Social Medicine)',
    sourceType: 'primary-research',
    tier: 'primary',
    url: 'https://demo.prism.invalid/transregional-maternal-cohort-2025',
    date: '2025-10-08',
    language: 'en',
    country: '泛洲（跨国机构）',
    credibility: 95,
    credibilityBasis: '经同行评审、预先登记，公开了统计代码与去标识化数据集，且随文刊出两位评审人的意见与作者的逐条回应。',
    accessedAt: '2026-08-26',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-amirat-penal-code-art-2023',
    title: 'قانون العقوبات — المواد المتعلقة بإنهاء الحمل（阿米拉特刑法典中涉及终止妊娠的条款）',
    publisher: '阿米拉特王国官方公报 (Official Gazette of the Kingdom of Amirat)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/amirat-penal-code-articles-2023',
    date: '2023-05-16',
    language: 'ar',
    country: '阿米拉特王国',
    credibility: 90,
    credibilityBasis: '官方公报刊出条文原文与修订沿革，文本本身可靠；但公报不包含检察与量刑实践，条文与实际执行之间的差距无从由此判断。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-veyra-supreme-repro-2024',
    title: 'Sentencia 402/2024 — autonomía corporal y consentimiento informado（韦拉最高法院第402/2024号判决：身体自主与知情同意）',
    publisher: '韦拉最高法院 (Supreme Court of Veyra)',
    sourceType: 'court-ruling',
    tier: 'primary',
    url: 'https://demo.prism.invalid/veyra-supreme-402-2024',
    date: '2024-09-05',
    language: 'es',
    country: '韦拉共和国',
    credibility: 93,
    credibilityBasis: '判决全文公开并附下级法院查明的事实清单，可以区分哪些是法院认定的事实、哪些只是当事人的主张。',
    accessedAt: '2026-08-28',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pancont-repro-observations-2026',
    title: 'Observations sur l’accès aux soins de santé reproductive（泛洲人权理事会关于生育健康服务可及性的意见）',
    publisher: '泛洲人权理事会 (Pan-Continental Human Rights Council)',
    sourceType: 'international-body',
    tier: 'primary',
    url: 'https://demo.prism.invalid/pancont-repro-observations-2026',
    date: '2026-02-19',
    language: 'fr',
    country: '泛洲（跨国机构）',
    credibility: 92,
    credibilityBasis: '意见逐段标注所依据的缔约国报告页码与实地访问记录编号，读者可以核对每项结论背后到底有几份材料。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-selva-preprint-contraception-2026',
    title: 'Acesso a contraceção de emergência: análise preliminar（紧急避孕可及性：初步分析——预印本）',
    publisher: '塞尔瓦公共卫生预印本平台 (Selva Public Health Preprint Server)',
    sourceType: 'primary-research',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/selva-preprint-contraception-2026',
    date: '2026-07-30',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 51,
    credibilityBasis: '作者公开了数据与代码，方法描述完整，但尚未经过任何同行评审，样本量与分组方式在评审中很可能被要求修改。',
    accessedAt: '2026-08-30',
    isPrimary: false,
    demo: true,
    caution: '未经同行评审的预印本。可以作为「有研究正在进行」的线索，不可作为结论性证据；引用时必须在正文中写明「预印本、尚未评审」。',
  },
  {
    id: 'src-norhold-repro-guidance-2025',
    title: 'National Clinical Guidance: Referral Pathways in Reproductive Care（北屿生育照护转诊路径国家临床指南）',
    publisher: '北屿国家临床指南委员会 (Norhold National Clinical Guidance Committee)',
    sourceType: 'other',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/norhold-repro-guidance-2025',
    date: '2025-06-24',
    language: 'en',
    country: '北屿联合王国',
    credibility: 80,
    credibilityBasis: '指南公开了证据评级表与委员名单的利益申报，但它规定的是应然流程，不能用来说明各地实际执行到什么程度。',
    accessedAt: '2026-08-26',
    isPrimary: false,
    demo: true,
  },

  /* ==================================================================== *
   * trans — 跨性别权利与医疗
   * ==================================================================== */
  {
    id: 'src-norhold-trans-health-alliance-2026',
    title: 'Waiting Times in Gender-Affirming Care: 2026 Service Audit（北屿跨性别健康联盟 2026 年服务等待时长审计）',
    publisher: '北屿跨性别健康联盟 (Norhold Trans Health Alliance)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/norhold-trans-health-waits-2026',
    date: '2026-06-02',
    language: 'en',
    country: '北屿联合王国',
    credibility: 81,
    credibilityBasis: '报告公开了向 11 家服务点发出的问卷原文、回收率与未回复名单，数据仍属自愿上报，未回复者可能等待更久。',
    accessedAt: '2026-08-24',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-norhold-recognition-bill-2026',
    title: 'Gender Recognition (Administrative Procedure) Bill 2026（北屿《性别承认（行政程序）法案 2026》）',
    publisher: '北屿联合王国议会法典局 (Norhold Parliamentary Statute Office)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/norhold-recognition-bill-2026',
    date: '2026-01-29',
    language: 'en',
    country: '北屿联合王国',
    credibility: 92,
    credibilityBasis: '法案文本、说明备忘录与委员会阶段的全部修正案一并公开，可核对某一程序要求究竟出现在哪一稿。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-transregional-trans-care-review-2025',
    title: 'Gender-affirming care outcomes: a systematic review of 41 cohorts（跨性别医疗结局：41 个队列的系统综述）',
    publisher: '《跨区域社会医学评论》(Transregional Review of Social Medicine)',
    sourceType: 'academic-review',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/transregional-care-review-2025',
    date: '2025-11-21',
    language: 'en',
    country: '泛洲（跨国机构）',
    credibility: 90,
    credibilityBasis: '综述登记了检索式与纳入排除标准，逐项标注了各原研究的偏倚风险，并明确指出长期随访证据仍然稀薄。',
    accessedAt: '2026-08-28',
    isPrimary: false,
    demo: true,
    notes: '这是对已有研究的二次综合，不是新的一手数据。',
  },
  {
    id: 'src-estria-east-clinic-decree-2025',
    title: 'Приказ о порядке оказания специализированной помощи（东埃斯特里亚关于专科医疗服务程序的部令）',
    publisher: '东埃斯特里亚卫生部 (Ministry of Health, East Estria)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/estria-east-clinic-decree-2025',
    date: '2025-04-15',
    language: 'ru',
    country: '东埃斯特里亚',
    credibility: 76,
    credibilityBasis: '部令原文在官方法规库可查、条文明确，但该法规库不提供历史版本，无法确认公布后是否被静默修改过。',
    accessedAt: '2026-08-29',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-estria-state-wire-clinics-2026',
    title: 'Сообщение о работе профильных клиник（东埃斯特里亚国家通讯社关于专科诊所运转的通稿）',
    publisher: '东埃斯特里亚国家通讯社 (East Estria State News Agency)',
    sourceType: 'news-agency',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/estria-state-wire-clinics-2026',
    date: '2026-07-06',
    language: 'ru',
    country: '东埃斯特里亚',
    credibility: 38,
    credibilityBasis: '通讯社由主管部门直接管辖，所在辖区对独立新闻报道设有许可限制，通稿中的数字无法由任何独立机构复核。',
    accessedAt: '2026-08-30',
    isPrimary: false,
    demo: true,
    caution: '国家控制的通讯社，且所在辖区存在新闻限制。可用于说明官方口径，不可作为事实依据；与之冲突的独立来源不应被它抵消。',
  },
  {
    id: 'src-turan-trans-survey-2026',
    title: 'Sağlık hizmetlerine erişim anketi 2026（图兰跨性别者医疗可及性调查 2026）',
    publisher: '图兰健康与权利协作组 (Turan Health & Rights Collaborative)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/turan-trans-access-survey-2026',
    date: '2026-05-19',
    language: 'tr',
    country: '图兰共和国',
    credibility: 73,
    credibilityBasis: '调查公布了问卷全文与招募渠道，但样本以滚雪球方式取得、集中在两座城市，机构本身也在报告首页说明不可推及全国。',
    accessedAt: '2026-08-25',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-pancont-recognition-index-2026',
    title: 'Index des procédures de reconnaissance de genre 2026（泛洲法律性别承认程序索引 2026）',
    publisher: '泛洲人权理事会法律比较处 (Pan-Continental Human Rights Council, Comparative Law Unit)',
    sourceType: 'international-body',
    tier: 'primary',
    url: 'https://demo.prism.invalid/pancont-recognition-index-2026',
    date: '2026-04-08',
    language: 'fr',
    country: '多辖区（跨国比较）',
    credibility: 88,
    credibilityBasis: '索引对每个辖区都列出所依据的成文法条款编号与编码规则，可逐条复核；但只编码法律文本，不测量实际办理时长与拒绝率。',
    accessedAt: '2026-08-26',
    isPrimary: true,
    demo: true,
  },

  /* ==================================================================== *
   * hate — 仇恨犯罪与网络暴力
   * ==================================================================== */
  {
    id: 'src-norhold-hate-crime-stats-2026',
    title: 'Recorded Hate Crime and Online Harassment Statistics 2026（北屿仇恨犯罪与网络骚扰记录统计 2026）',
    publisher: '北屿内政统计办公室 (Norhold Home Statistics Office)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/norhold-hate-crime-stats-2026',
    date: '2026-04-30',
    language: 'en',
    country: '北屿联合王国',
    credibility: 83,
    credibilityBasis: '统计办公室随数据发布方法说明与已知偏差清单，并主动标注 2023 年在线报案入口上线对报案量的影响，但仍只反映报案而非发生率。',
    accessedAt: '2026-08-24',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-norhold-online-abuse-study-2025',
    title: 'Coordinated harassment campaigns against women in public life（针对公共生活中女性的协同骚扰研究）',
    publisher: '北屿开放大学网络治理研究组 (Norhold Open University, Network Governance Group)',
    sourceType: 'primary-research',
    tier: 'primary',
    url: 'https://demo.prism.invalid/norhold-open-university-harassment-2025',
    date: '2025-07-14',
    language: 'en',
    country: '北屿联合王国',
    credibility: 90,
    credibilityBasis: '研究经同行评审，公开了账号采样框、协同判定阈值与人工复核的一致性系数，并说明了平台限流导致的取样缺口。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
    notes: '研究机构设于北屿联合王国，取样覆盖四个辖区的公开账号；引用跨辖区结论时应说明取样范围。',
  },
  {
    id: 'src-tideline-platform-transparency-2026',
    title: 'Tideline Network Transparency Report H1 2026（潮线网络 2026 上半年透明度报告）',
    publisher: '潮线网络 (Tideline Network)',
    sourceType: 'other',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/tideline-transparency-h1-2026',
    date: '2026-06-15',
    language: 'en',
    country: '多辖区（跨国比较）',
    credibility: 64,
    credibilityBasis: '平台自行统计并自行发布，分类定义每年变动且不接受外部审计，但至少公布了各类处置的绝对数与申诉改判比例。',
    accessedAt: '2026-08-28',
    isPrimary: false,
    demo: true,
    notes: '自我报告数据。与用户端举报记录对照时经常对不上，引用时应写明「平台自述」。',
  },
  {
    id: 'src-turan-outlet-corrections-2025',
    title: 'Çevrim içi taciz dosyası（图兰某新闻网站的网络骚扰专题）',
    publisher: '晨线新闻网 (Morning Line News)',
    sourceType: 'local-media',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/morning-line-harassment-file-2025',
    date: '2025-09-12',
    language: 'tr',
    country: '图兰共和国',
    credibility: 46,
    credibilityBasis: '该网站在过去两年内被自家更正栏记录了 19 次事实性更正，其中 6 次涉及数字或身份误植，且多数更正未在原文页面标注。',
    accessedAt: '2026-08-29',
    isPrimary: false,
    demo: true,
    caution: '有据可查的更正问题：更正频次高且不在原文标注。该网站的任何具体数字都必须另找一手来源印证后才可使用。',
  },
  {
    id: 'src-kalisan-hate-amendment-2025',
    title: 'दंड संहिता संशोधन — घृणा अपराध धाराएँ（卡利桑刑法典仇恨犯罪条款修正案）',
    publisher: '卡利桑邦立法公报 (Kalisan State Legislative Gazette)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/kalisan-hate-crime-amendment-2025',
    date: '2025-02-26',
    language: 'hi',
    country: '卡利桑邦',
    credibility: 88,
    credibilityBasis: '修正案条文与生效公告在立法公报同期刊出，附有被修改条款的新旧对照表，可精确核对增删了哪些受保护特征。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-maran-partisan-bulletin-2026',
    title: 'Buletin kampanye: menolak agenda asing（马兰岛某竞选阵营的宣传通讯）',
    publisher: '马兰岛「群岛之家」竞选阵营 (Maran “Archipelago Home” Campaign)',
    sourceType: 'other',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/maran-campaign-bulletin-2026',
    date: '2026-08-02',
    language: 'id',
    country: '马兰岛自治区',
    credibility: 44,
    credibilityBasis: '竞选材料的目的是动员而非记录，通讯中引用的三项统计均未注明出处，其中一项与自治区统计口径明显不符。',
    accessedAt: '2026-08-30',
    isPrimary: false,
    demo: true,
    caution: '党派竞选材料。只能用于说明该阵营的主张与话语策略，不能作为事实来源；若引用其数字，必须同时给出该数字无法核实的说明。',
  },

  /* ==================================================================== *
   * equality — 法律、政治、教育、医疗与职场平等
   * ==================================================================== */
  {
    id: 'src-norhold-pay-audit-2026',
    title: 'Statutory Pay Gap Audit Return 2026（北屿法定薪酬差距申报汇总 2026）',
    publisher: '北屿平等事务监察署 (Norhold Equality Inspectorate)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/norhold-pay-gap-audit-2026',
    date: '2026-03-25',
    language: 'en',
    country: '北屿联合王国',
    credibility: 91,
    credibilityBasis: '所有满足门槛的雇主必须依法申报，监察署公开逐家的原始申报值与迟报名单，任何汇总数字都能被重新计算。',
    accessedAt: '2026-08-24',
    isPrimary: true,
    demo: true,
    notes: '只覆盖雇员人数超过法定门槛的雇主，非正规就业完全不在其中。',
  },
  {
    id: 'src-selva-labour-court-2025',
    title: 'Acórdão do Tribunal do Trabalho — discriminação na promoção（塞尔瓦劳动法院判决：晋升歧视案）',
    publisher: '塞尔瓦联邦劳动法院 (Federal Labour Court of Selva)',
    sourceType: 'court-ruling',
    tier: 'primary',
    url: 'https://demo.prism.invalid/selva-labour-court-promotion-2025',
    date: '2025-06-11',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 90,
    credibilityBasis: '判决书公开了法院采信的薪酬回归分析全文与被告提交的原始人事数据摘要，可以看出法院据以推论的具体依据。',
    accessedAt: '2026-08-26',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-kalisan-enrolment-stats-2025',
    title: 'माध्यमिक शिक्षा नामांकन सांख्यिकी 2025（卡利桑中学阶段入学统计 2025）',
    publisher: '卡利桑统计局 (Kalisan Bureau of Statistics)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/kalisan-enrolment-2025',
    date: '2025-10-20',
    language: 'hi',
    country: '卡利桑邦',
    credibility: 82,
    credibilityBasis: '按县与性别公开分列的入学与留级数据，并附学校上报的时点说明；但辍学定义在两年前调整过，跨年比较需要额外换算。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-transregional-care-labour-2026',
    title: 'Unpaid care work and labour-market attachment: a review（无酬照护劳动与劳动力市场参与：综述）',
    publisher: '《跨区域社会医学评论》(Transregional Review of Social Medicine)',
    sourceType: 'academic-review',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/transregional-care-labour-2026',
    date: '2026-01-16',
    language: 'en',
    country: '泛洲（跨国机构）',
    credibility: 87,
    credibilityBasis: '综述公开检索式与纳入标准，明确指出所纳入研究多来自高收入辖区，因而对其他地区的外推能力有限。',
    accessedAt: '2026-08-28',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-norhold-campaign-statement-2026',
    title: 'Campaign statement on the pay audit figures（某竞选团队关于薪酬审计数字的声明）',
    publisher: '北屿「务实前进」竞选团队 (Norhold “Practical Forward” Campaign)',
    sourceType: 'statement',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/norhold-campaign-pay-statement-2026',
    date: '2026-07-28',
    language: 'en',
    country: '北屿联合王国',
    credibility: 41,
    credibilityBasis: '党派声明重新加权了官方审计数据却未公布加权方法，被引用的两个百分比无法用监察署公开的原始申报值复现。',
    accessedAt: '2026-08-29',
    isPrimary: false,
    demo: true,
    caution: '党派立场声明，且对官方数据做了未公开方法的再加工。仅可作为「某方如何解读数据」的材料；必须与监察署原始申报值并列呈现。',
  },
  {
    id: 'src-estria-west-audit-office-2026',
    title: 'Отчёт Счётной палаты о равной оплате труда（西埃斯特里亚审计署同工同酬报告）',
    publisher: '西埃斯特里亚审计署 (Court of Audit, West Estria)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/estria-west-audit-equal-pay-2026',
    date: '2026-02-05',
    language: 'ru',
    country: '西埃斯特里亚',
    credibility: 85,
    credibilityBasis: '审计署独立于被审计部门、报告须提交议会公开辩论，并附被审计单位的反驳意见全文，可以看到双方分歧所在。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pancont-equality-panel-2026',
    title: 'Panel régional sur l’écart salarial 2025（泛洲区域薪酬差距面板数据 2025）',
    publisher: '泛洲人权理事会经济与社会权利处 (Pan-Continental Human Rights Council, Economic & Social Rights Unit)',
    sourceType: 'international-body',
    tier: 'primary',
    url: 'https://demo.prism.invalid/pancont-pay-gap-panel-2025',
    date: '2026-05-07',
    language: 'fr',
    country: '多辖区（跨国比较）',
    credibility: 89,
    credibilityBasis: '面板数据统一了各辖区的口径并公布了换算规则与每个数值的原始出处，但仍以各辖区自报的行政数据为基础。',
    accessedAt: '2026-08-26',
    isPrimary: true,
    demo: true,
  },

  /* ==================================================================== *
   * displacement — 战争、移民及交叉边缘群体
   * ==================================================================== */
  {
    id: 'src-pancont-displacement-observations-2026',
    title: 'Observations sur la protection des personnes déplacées（泛洲人权理事会关于流离失所者保护的意见）',
    publisher: '泛洲人权理事会 (Pan-Continental Human Rights Council)',
    sourceType: 'international-body',
    tier: 'primary',
    url: 'https://demo.prism.invalid/pancont-displacement-observations-2026',
    date: '2026-06-25',
    language: 'fr',
    country: '泛洲（跨国机构）',
    credibility: 94,
    credibilityBasis: '意见基于两次实地访问与 63 份提交材料，每项结论都标注了材料编号与访问日期，并列出被拒绝进入的地点清单。',
    accessedAt: '2026-08-24',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-amirat-border-decree-2025',
    title: 'مرسوم بشأن إجراءات الحدود والإقامة المؤقتة（阿米拉特关于边境程序与临时居留的法令）',
    publisher: '阿米拉特王国官方公报 (Official Gazette of the Kingdom of Amirat)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/amirat-border-decree-2025',
    date: '2025-03-19',
    language: 'ar',
    country: '阿米拉特王国',
    credibility: 86,
    credibilityBasis: '法令文本在官方公报完整刊出并注明生效日；但配套的执行细则未公开，条文与口岸实际做法之间的差距无法由此判断。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-border-voices-shelter-2026',
    title: 'أصوات الحدود: ثلاثة أشهر في مركز الاستقبال（边界之声：接待中心的三个月）',
    publisher: '边界之声 (Border Voices)',
    sourceType: 'local-media',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/border-voices-reception-2026',
    date: '2026-07-17',
    language: 'ar',
    country: '阿米拉特王国',
    credibility: 72,
    credibilityBasis: '报道基于记者三个月的现场蹲点与 21 份可查的登记文件，但受访者出于安全考虑全部匿名，第三方无法回访核实。',
    accessedAt: '2026-08-28',
    isPrimary: false,
    demo: true,
    notes: '受访者匿名系出于报复风险，编辑部保留了匿名依据的内部记录。',
  },
  {
    id: 'src-selva-asylum-tribunal-2026',
    title: 'Decisões do Tribunal de Asilo — motivos de género e orientação sexual（塞尔瓦庇护法庭：性别与性取向理由裁决汇编）',
    publisher: '塞尔瓦联邦庇护法庭 (Federal Asylum Tribunal of Selva)',
    sourceType: 'court-ruling',
    tier: 'primary',
    url: 'https://demo.prism.invalid/selva-asylum-tribunal-2026',
    date: '2026-05-22',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 89,
    credibilityBasis: '法庭公开了去标识化的裁决全文与年度结果统计表，并附分类编码手册，可核对「程序终止」等类目的判定标准。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-maran-sea-rescue-network-2025',
    title: 'Laporan tahunan jaringan penyelamatan laut（马兰岛海上救援与庇护网络年度报告）',
    publisher: '马兰岛海上救援与庇护网络 (Maran Sea Rescue & Shelter Network)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/maran-sea-rescue-annual-2025',
    date: '2025-12-03',
    language: 'id',
    country: '马兰岛自治区',
    credibility: 77,
    credibilityBasis: '报告附有逐次出航的航次记录与经费审计意见，数据只覆盖该网络自身参与的救援，其他行动者的案例不在其中。',
    accessedAt: '2026-08-29',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-estria-west-stateless-registry-2025',
    title: 'Реестр лиц без гражданства — сводные показатели（西埃斯特里亚无国籍人员登记汇总指标）',
    publisher: '西埃斯特里亚民事登记总局 (General Directorate of Civil Registration, West Estria)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/estria-west-stateless-registry-2025',
    date: '2025-08-28',
    language: 'ru',
    country: '西埃斯特里亚',
    credibility: 69,
    credibilityBasis: '登记数据由官方直接产出、字段定义公开，但只统计已主动申请登记者，机构自己在说明中估计覆盖率不足七成。',
    accessedAt: '2026-08-30',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-norhold-diaspora-legal-aid-2026',
    title: '《移民妇女法律求助个案年度观察 2026》(Diaspora Women’s Legal Aid Annual Casework Review)',
    publisher: '北屿华语移民妇女法律互助会 (Norhold Chinese-Speaking Migrant Women’s Legal Aid Mutual Society)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/norhold-diaspora-legal-aid-2026',
    date: '2026-04-18',
    language: 'zh-Hans',
    country: '北屿联合王国',
    credibility: 77,
    credibilityBasis: '报告写明个案计数规则、翻译流程与匿名处理方式，并公布了自身经费来源；样本仅限主动求助者，不能推及全体移民妇女。',
    accessedAt: '2026-08-26',
    isPrimary: false,
    demo: true,
  },

  /* ==================================================================== *
   * movement — 运动内部的重要争议
   * ==================================================================== */
  {
    id: 'src-pancont-funding-review-2026',
    title: 'Revue des flux de financement de la société civile 2025（泛洲公民社会资金流向审视 2025）',
    publisher: '泛洲公民社会资金观察 (Pan-Continental Civic Funding Observatory)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/pancont-civic-funding-review-2026',
    date: '2026-03-04',
    language: 'fr',
    country: '多辖区（跨国比较）',
    credibility: 80,
    credibilityBasis: '公布了问卷全文、214 家填报机构的分布与自身资助方名单，但填报出于自愿，受限环境中的组织普遍缺席。',
    accessedAt: '2026-08-24',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-veyra-coalition-letter-2026',
    title: 'Carta abierta de la coalición sobre criterios de inclusión（韦拉某联盟关于包容性标准的公开信）',
    publisher: '韦拉女性主义组织联盟 (Coalition of Feminist Organisations of Veyra)',
    sourceType: 'statement',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/veyra-coalition-open-letter-2026',
    date: '2026-06-09',
    language: 'es',
    country: '韦拉共和国',
    credibility: 63,
    credibilityBasis: '公开信附有 47 家署名组织的完整名单与各自的联系方式，立场表述清楚，但其中关于资金分配的三处指控未附任何凭据。',
    accessedAt: '2026-08-27',
    isPrimary: false,
    demo: true,
    notes: '可作为立场文本引用；其中的事实性指控须另行核实。',
  },
  {
    id: 'src-transregional-movement-fieldwork-2025',
    title: 'Coalition-building under resource scarcity: a multi-site ethnography（资源紧缩下的联盟构建：多点民族志）',
    publisher: '《跨区域社会医学评论》社会科学专刊 (Transregional Review of Social Medicine, Social Science Special Issue)',
    sourceType: 'primary-research',
    tier: 'primary',
    url: 'https://demo.prism.invalid/transregional-movement-ethnography-2025',
    date: '2025-05-13',
    language: 'en',
    country: '多辖区（跨国比较）',
    credibility: 86,
    credibilityBasis: '经同行评审，公开了田野时长、编码簿与研究者立场声明；样本为四个辖区的六家组织，作者明确表示不追求代表性。',
    accessedAt: '2026-08-28',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-norhold-assembly-minutes-2026',
    title: 'Published Minutes: Movement Assembly, Spring 2026（2026 年春季运动大会公开会议记录）',
    publisher: '北屿平等组织常设大会秘书处 (Standing Assembly Secretariat, Norhold Equality Organisations)',
    sourceType: 'other',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/norhold-assembly-minutes-2026',
    date: '2026-02-27',
    language: 'en',
    country: '北屿联合王国',
    credibility: 70,
    credibilityBasis: '会议记录经与会方书面确认后公布并附表决票数，但记录经过秘书处摘要处理，发言原话与被删节的部分无法还原。',
    accessedAt: '2026-08-25',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-maran-coastal-collective-2026',
    title: 'Kiungo cha Visiwa: mgawanyiko wa vipaumbele（岛链通讯：优先事项的分裂）',
    publisher: '岛链通讯 (Kiungo cha Visiwa)',
    sourceType: 'local-media',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/kiungo-cha-visiwa-priorities-2026',
    date: '2026-07-11',
    language: 'sw',
    country: '马兰岛自治区',
    credibility: 66,
    credibilityBasis: '社区媒体直接采访了争议双方并刊出双方来函全文，但编辑部只有两名兼职人员，未对会议记录等书面材料做独立核对。',
    accessedAt: '2026-08-29',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-turan-agency-movement-split-2026',
    title: 'Kadın örgütleri arasında strateji ayrışması（图兰独立新闻社：妇女组织之间的策略分歧）',
    publisher: '图兰独立新闻社 (Turan Independent News Agency)',
    sourceType: 'news-agency',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/turan-agency-movement-split-2026',
    date: '2026-08-06',
    language: 'tr',
    country: '图兰共和国',
    credibility: 76,
    credibilityBasis: '通讯社取得并公布了两份内部会议纪要的影印件，且给了被批评一方完整回应空间，但纪要的真实性未经第三方鉴定。',
    accessedAt: '2026-08-30',
    isPrimary: false,
    demo: true,
  },

  /* ==================================================================== *
   * 候选来源池 — 尚未被任何稿件采用
   * 「要求增加来源」流程从这里挑选补强材料。
   * ==================================================================== */
  {
    id: 'src-pool-veyra-appellate-docket-2026',
    title: 'Registro de causas — Cámara de Apelaciones de Veyra（韦拉上诉法院案件登记簿）',
    publisher: '韦拉上诉法院书记处 (Registry, Court of Appeal of Veyra)',
    sourceType: 'court-ruling',
    tier: 'primary',
    url: 'https://demo.prism.invalid/veyra-appellate-docket-2026',
    date: '2026-07-09',
    language: 'es',
    country: '韦拉共和国',
    credibility: 90,
    credibilityBasis: '登记簿逐案列出立案日、审理阶段与终结方式，可以直接核对某一案件是否仍在审理，避免把指控写成已决事实。',
    accessedAt: '2026-08-28',
    isPrimary: true,
    demo: true,
    notes: '适合用来确认某案的司法阶段，避免「指控／判决」混用。',
  },
  {
    id: 'src-pool-kalisan-shelter-budget-2026',
    title: 'आश्रय गृह बजट आवंटन 2026（卡利桑庇护所预算拨付明细 2026）',
    publisher: '卡利桑邦财政厅 (Kalisan State Department of Finance)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/kalisan-shelter-budget-2026',
    date: '2026-06-13',
    language: 'hi',
    country: '卡利桑邦',
    credibility: 81,
    credibilityBasis: '预算文件按县列出拨付额与执行率，可与床位统计交叉核对；但只反映拨付而非实际到账时间，延付情况需另行查证。',
    accessedAt: '2026-08-26',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pool-norhold-committee-evidence-2026',
    title: 'Select Committee Evidence Session: Gender Recognition Bill（北屿专责委员会性别承认法案证据听证记录）',
    publisher: '北屿联合王国议会委员会办公室 (Norhold Parliamentary Committee Office)',
    sourceType: 'legal-document',
    tier: 'primary',
    url: 'https://demo.prism.invalid/norhold-committee-evidence-2026',
    date: '2026-05-30',
    language: 'en',
    country: '北屿联合王国',
    credibility: 84,
    credibilityBasis: '逐字记录与书面证据全文公开且标注提交方身份，可核对某一说法究竟由谁在何时提出；但证人陈述本身未经委员会核实。',
    accessedAt: '2026-08-25',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pool-selva-cohort-followup-2026',
    title: 'Seguimento de coorte a 24 meses: acesso a cuidados（24 个月队列随访：照护可及性）',
    publisher: '塞尔瓦国家卫生研究所 (Selva National Institute of Health)',
    sourceType: 'primary-research',
    tier: 'primary',
    url: 'https://demo.prism.invalid/selva-cohort-followup-2026',
    date: '2026-04-02',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 89,
    credibilityBasis: '经同行评审的随访研究，公开了失访率（11%）与敏感性分析，明确说明失访者可能系统性地更难获得照护。',
    accessedAt: '2026-08-27',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pool-pancont-rapporteur-visit-2026',
    title: 'Rapport de visite du rapporteur spécial — Turan（泛洲特别报告员图兰访问报告）',
    publisher: '泛洲人权理事会特别程序 (Pan-Continental Human Rights Council, Special Procedures)',
    sourceType: 'international-body',
    tier: 'primary',
    url: 'https://demo.prism.invalid/pancont-rapporteur-turan-2026',
    date: '2026-07-24',
    language: 'fr',
    country: '泛洲（跨国机构）',
    credibility: 92,
    credibilityBasis: '访问报告列出全部会面机构、被拒绝进入的场所与政府的书面答复，读者可以看清哪些结论建立在直接观察之上。',
    accessedAt: '2026-08-29',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pool-amirat-court-transcript-2025',
    title: 'محضر جلسة محكمة الاستئناف（阿米拉特上诉法院庭审笔录）',
    publisher: '阿米拉特王国上诉法院 (Court of Appeal, Kingdom of Amirat)',
    sourceType: 'court-ruling',
    tier: 'primary',
    url: 'https://demo.prism.invalid/amirat-appeal-transcript-2025',
    date: '2025-11-27',
    language: 'ar',
    country: '阿米拉特王国',
    credibility: 87,
    credibilityBasis: '庭审笔录逐句记录并经审判长签署，可用于区分控方主张与法院认定；但公开版本对部分证人陈述做了遮蔽处理。',
    accessedAt: '2026-08-24',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pool-turan-union-survey-2026',
    title: 'İşyeri taciz anketi — sendika üyeleri（图兰工会会员职场骚扰调查）',
    publisher: '图兰服务业工会联合会 (Turan Federation of Service Sector Unions)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/turan-union-workplace-survey-2026',
    date: '2026-03-16',
    language: 'tr',
    country: '图兰共和国',
    credibility: 74,
    credibilityBasis: '调查公布了抽样框、回收率（38%）与问卷全文，但仅覆盖已加入工会的雇员，非正规就业者完全不在样本内。',
    accessedAt: '2026-08-26',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-pool-maran-clinic-ledger-2026',
    title: 'Register layanan klinik distrik 2026（马兰岛县级诊所服务登记册 2026）',
    publisher: '马兰岛自治区卫生局 (Maran Islands Autonomous Region Health Office)',
    sourceType: 'government-data',
    tier: 'primary',
    url: 'https://demo.prism.invalid/maran-clinic-ledger-2026',
    date: '2026-06-20',
    language: 'id',
    country: '马兰岛自治区',
    credibility: 78,
    credibilityBasis: '登记册按月上报、字段定义公开，可核对服务量变化；但三个离岛诊所长期漏报，卫生局已在扉页标注这一缺口。',
    accessedAt: '2026-08-28',
    isPrimary: true,
    demo: true,
  },
  {
    id: 'src-pool-estria-west-ombuds-reply-2026',
    title: 'Ответ уполномоченного на запрос о данных（西埃斯特里亚监察专员对数据查询的书面答复）',
    publisher: '西埃斯特里亚人权监察专员办公室 (Office of the Human Rights Ombuds, West Estria)',
    sourceType: 'other',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/estria-west-ombuds-reply-2026',
    date: '2026-08-11',
    language: 'ru',
    country: '西埃斯特里亚',
    credibility: 66,
    credibilityBasis: '书面答复由机构签发、可作为其立场的确证，但只给出投诉总数而拒绝提供分类明细，理由是「统计口径尚未统一」。',
    accessedAt: '2026-08-30',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-pool-coastline-archive-2024',
    title: 'Arquivo: cobertura do processo em 2024（海岸线报 2024 年该案报道存档）',
    publisher: '海岸线报 (Coastline Daily)',
    sourceType: 'local-media',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/coastline-archive-2024',
    date: '2024-11-08',
    language: 'pt',
    country: '塞尔瓦联邦',
    credibility: 69,
    credibilityBasis: '存档提供了两年前的报道原文与其后的更正记录，适合核对时间线；早期报道对案件阶段的表述后来被该报自行更正过一次。',
    accessedAt: '2026-08-25',
    isPrimary: false,
    demo: true,
    notes: '用于时间线交叉核对时，应以其后的更正版本为准。',
  },
  {
    id: 'src-pool-aggregator-screenshots-2026',
    title: '「每日汇总」账号发布的截图合辑（Screenshot compilation from an aggregation account）',
    publisher: '匿名聚合账号（无编辑部、无更正政策）',
    sourceType: 'social-post',
    tier: 'tertiary',
    url: 'https://demo.prism.invalid/aggregator-screenshots-2026',
    date: '2026-08-19',
    language: 'zh-Hans',
    country: '多辖区（跨国比较）',
    credibility: 36,
    credibilityBasis: '账号只转发截图、从不给出原始链接，抽查其中五张截图有两张无法对应到任何可查的原始发布，且账号无更正记录。',
    accessedAt: '2026-08-31',
    isPrimary: false,
    demo: true,
    caution: '截图聚合账号，无法回溯到原始发布。仅可用来说明某说法的传播路径；任何引用都必须先找到截图对应的原始记录。',
  },
  {
    id: 'src-pool-transregional-methods-note-2026',
    title: 'Methods note: comparing administrative counts across jurisdictions（方法说明：跨辖区行政统计的可比性）',
    publisher: '《跨区域社会医学评论》(Transregional Review of Social Medicine)',
    sourceType: 'academic-review',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/transregional-methods-note-2026',
    date: '2026-02-12',
    language: 'en',
    country: '泛洲（跨国机构）',
    credibility: 88,
    credibilityBasis: '经评审的方法学说明，逐条列出行政统计跨辖区比较的失效条件，并给出可复算的换算示例，适合用来限定图表结论。',
    accessedAt: '2026-08-27',
    isPrimary: false,
    demo: true,
    notes: '适合在做跨辖区比较图表时引用，用来说明「为什么不能直接比」。',
  },
  {
    id: 'src-pool-maran-language-access-2025',
    title: 'Upatikanaji wa huduma kwa lugha ya jamii（社区语言的服务可及性调查）',
    publisher: '马兰岛语言服务互助会 (Maran Islands Language Access Mutual Aid)',
    sourceType: 'ngo-report',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/maran-language-access-2025',
    date: '2025-07-05',
    language: 'sw',
    country: '马兰岛自治区',
    credibility: 75,
    credibilityBasis: '报告记录了 312 次陪同就医与报案的现场观察，方法与观察表公开；但观察对象全部来自求助渠道，选择性偏差明显。',
    accessedAt: '2026-08-29',
    isPrimary: false,
    demo: true,
  },
  {
    id: 'src-pool-veyra-agency-followup-2026',
    title: 'Seguimiento: qué cambió tras la sentencia（跟进报道：判决之后有什么改变）',
    publisher: '韦拉区域通讯社 (Veyra Regional News Agency)',
    sourceType: 'news-agency',
    tier: 'secondary',
    url: 'https://demo.prism.invalid/veyra-agency-followup-2026',
    date: '2026-08-13',
    language: 'es',
    country: '韦拉共和国',
    credibility: 79,
    credibilityBasis: '通讯社有公开的更正政策与署名制度，本篇采访了六家登记机构并附上问询与答复原文，但未取得主管部门的整体数据。',
    accessedAt: '2026-08-31',
    isPrimary: false,
    demo: true,
  },
]
